server:
  port: 8081
  servlet:
      context-path: /horarios/api
spring:
  datasource:
    url: jdbc:mysql://${HOST_NAME:127.0.0.1}:${BD_PORT:3311}/${BD_NAME:calcbecabd}?useSSL=false
    #url: jdbc:mysql://${HOST_NAME:192.160.0.12}:${BD_PORT:3306}/${BD_NAME:calcbecabd}?useSSL=false
    username: ${BD_USER:dbuser}
    password: ${BD_PASS:dbpassword}
key:
  encode:
    crypto: $#u1!N51*5M412&
location:
  file: /Users/lmarcoss/workspace-leo/servicio-social/file-dev/

prop:
  carga:
    hrs:
      biblioteca:
        id: 1
        posicion:
          matricula: 1
          nombre: 2
          horas: 3
          celda:
            final: 4
      sala:
        id: 2
        posicion:
          matricula: 1
          nombre: 2
          asistencia:
            inicio: 3
        asistencia:
          asistencia: .
          falta: /