package edu.calc.becas.mconfiguracion.login.dao;

public class QueriesLogin {

  static final String QRY_GET_INFO_LOGIN ="SELECT ID_USUARIO,NOMBRES, APE_PATERNO, APE_MATERNO, ID_ROL, (SELECT NOMBRE_ROL FROM ROLES R WHERE R.ID_ROL = USU.ID_ROL) ROL, USERNAME FROM USUARIOS USU\n" +
    "WHERE USERNAME = ?\n" +
    "UNION\n" +
    "SELECT ID_ALUMNO,NOMBRES, APE_PATERNO, APE_MATERNO, '3' ID_ROL, 'ALUMNO' ROL, MATRICULA as USERNAME FROM ALUMNOS AL\n" +
    "WHERE MATRICULA = ?";
}
